### ISSUE TITLE
Unable to inspect any file.

### ISSUE THREAD

**Issue by mattgrill** [patrickocoffeyo/whats#1]
With this tool I'm unable to inspect any file. For example when trying to `whats` a valid JSON file (`composer.json`) the following error is returned. `{ [Error: 404 Not Found: composer.json] code: 'E404', pkgid: 'composer.json’ }`.

- `node -v` `v0.12.4`
- `npm -v` `2.10.1`

**Comment by patrickocoffeyo** [comment]
@mattgrill,
Thank you for filing an issue. You have installed [this](https://www.npmjs.com/package/whats) npm module as opposed to whatis. Try running `npm install whatis`.
